/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.gioppo.projetoathena.visao;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import me.gioppo.projetoathena.controladores.ControladorFuncionarios;
import me.gioppo.projetoathena.modelo.Funcionario;

/**
 *
 * @author alisonbnt
 */
public class PainelListaFuncionarios extends javax.swing.JPanel implements PainelTrocavel{

    private final ControladorFuncionarios controladorFuncionarios;
    
    public PainelListaFuncionarios(ControladorFuncionarios controladorFuncionarios) {
        this.controladorFuncionarios = controladorFuncionarios;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout());

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "CPF", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaFuncionarios);
        if (tabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            tabelaFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            tabelaFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            tabelaFuncionarios.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2);

        add(jPanel1);

        jButton1.setText("Voltar ao menu principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControleDeTela.mudarPainel(ControleDeTela.TELA_MENU);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaFuncionarios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void acoesQuandoTrocar() {
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
        
        model.setRowCount(0);
        
        List<Funcionario> todosOsFuncionarios = controladorFuncionarios.listarFuncionarios();
        for (Funcionario funcionario : todosOsFuncionarios) {
            model.addRow(new Object[] { funcionario.getPrimeiroNome(), funcionario.getSobrenome(), funcionario.getCpf().getCpfFormatado(), "..."});
        }
        
        revalidate();
        repaint();
    }
}
